### ISSUE TITLE
new suggested rules

### ISSUE THREAD

**Issue by WaleedAshraf** [relayr/eslint-config-relayr#12]
https://eslint.org/docs/rules/comma-dangle
We already have it. I suggest we change it to this,
```js
'comma-dangle': ["warn", {
      "arrays": "always-multiline",
      "objects": "always-multiline",
      "imports": "always-multiline",
      "exports": "always-multiline",
      "functions": "never"
    }],
```

https://eslint.org/docs/rules/no-multi-spaces
warn.

https://eslint.org/docs/rules/require-jsdoc
warn. Always require JSDoc.

https://eslint.org/docs/rules/arrow-parens
warn with "as-needed"

https://eslint.org/docs/rules/curly
Not sure what's best here.

https://eslint.org/docs/rules/brace-style
 ["warn", "1tbs", { "allowSingleLine": true }],

https://eslint.org/docs/rules/space-before-function-paren
Always, warn.

https://eslint.org/docs/rules/no-invalid-this
off this one.

https://eslint.org/docs/rules/no-prototype-builtins
warn

https://eslint.org/docs/rules/no-trailing-spaces
warn

Later on, these will be charged to Errors.
cc @relayr/nodejs

**Comment by WaleedAshraf** [comment]
I there's no objection by this week, I'll add/update these rules at the "warn" level. cc @relayr/nodejs

**Comment by yuvke** [comment]
@WaleedAshraf  Some comments:
https://eslint.org/docs/rules/no-prototype-builtins
I would prefer to instead agree that we don't shadow `Object.prototype` methods, and do not create objects that do not inherit from `Object.prototype`. I never had the need of doing that and the safe way proposed here is so much more verbose that I don't see the value.

https://eslint.org/docs/rules/no-invalid-this
What's wrong with this rule?

https://eslint.org/docs/rules/arrow-parens
I would prefer:
` "as-needed", { "requireForBlockBody": true } ` (on warn)

https://eslint.org/docs/rules/curly
I would use "all" (on warn)

**Comment by WaleedAshraf** [comment]
@yuvke 
For prototype, we use `hasOwnProperty` at some places, to check if the property is defined or not.

For .this,
We use it at many places, in tests, especially, because `mocha` as some attributes defined at different scopes.

For parens,
I'm good with your suggestion.

For curly,
At many places, we do this,
```js
if (...) throw new Error()

or

if (...)
	do This
else
	do That
```
I like having one-liner if/else where possible. But it should be consistent. It think we can turn this rule off and review on PRs.

**Comment by Richard-Boyewa** [comment]
@WaleedAshraf what do you mean by **off this one**. on this rule https://eslint.org/docs/rules/no-invalid-this ?

**Comment by yuvke** [comment]
@WaleedAshraf maybe I didn't understand this rule correctly:
https://eslint.org/docs/rules/no-prototype-builtins
But to my understanding it says you can no longer do:
``` javascript
const obj = {}
obj.hasOwnProperty("bar")
```
and instead you need to do:
``` javascript
const obj = {}
Object.prototype.hasOwnProperty.call(obj, "bar");
```
To me, this is excessive since the use case we're trying to protect against does not (or shouldn't) exist (e.g. shadowing prototype methods or creating objects that don't inherit from Object.prototype).

regarding `this`, in my opinion, test folders can have their own subset of lint rules. There are a lot of edge cases where you want to be more linient in your test files. Also this enables you to specify (for example) that the files in this folder are run by mocha (which isn't the case for all the rest of the files in the repo).

Regarding curly, I think this is almost an aesthetic decision. If we can't reach a consensus (which we should), then let's not have the rule and also not discus it on PRs.

**Comment by WaleedAshraf** [comment]
@Richard-Boyewa @yuvke 
https://eslint.org/docs/rules/no-invalid-this 
I think you are right. We should turn this on at the warn level.


https://eslint.org/docs/rules/no-prototype-builtins
@yuvke what would be your suggestion for this use case? How should we do it?


Regarding curly, yup agreed. Not create rule, not discuss on PR. Have a general best practice to keep it consistent.

**Comment by yuvke** [comment]
@WaleedAshraf After your comment I did a little more digging about this rule, and I understand now that the main protection it gives is when you're using `.hasOwnProperty()` on objects that weren't created by your code. This is a valid scenario so I remove my objection. I still would prefer if we do
``` javascript
Object.prototype.hasOwnProperty.call(obj, "bar");
```
instead of
``` javascript
Object.prototype.hasOwnProperty.call(obj, "bar");
```
Or even have a tiny util for that (we can have a very small underscore-like lib):
``` javascript
module.exports = {
  hasOwnProp(obj, key) {
    return Object.prototype.hasOwnProperty.call(obj, key);
  }
}
```

**Comment by WaleedAshraf** [comment]
Why would you prefer `{}.prototype....` ?

I like the idea of having own tiny lodash/_ like lib....maybe in the future. 🎉

**Comment by yuvke** [comment]
> Why would you prefer `{}.prototype....` ?
It's shorter 😄

**Comment by WaleedAshraf** [comment]
To me, that's not enough reason. :p 
I'll suggest sticking with 
```
Object.prototype.hasOwnProperty.call(obj, "bar");
```

**Comment by yuvke** [comment]
They both pass the linting rule, so as long as we leave it up for the discretion of the coder I'm fine with just not commenting on this in PRs.

**Comment by WaleedAshraf** [comment]
@relayr/nodejs 
Also, thoughts on this one: https://eslint.org/docs/rules/one-var

**Comment by bernardpletikosa** [comment]
@WaleedAshraf should we close the list of rules, agree on them and add it to the lib rather than adding more rules for discussion in this PR?

curly - should allow one liner, for any if-else I would put the brackets for readability
prototype - linting rule 👍 . Re using `{}` instead of `Object` introduces unclarity imho and it's not worth couple of saved characters :)
